### ISSUE TITLE
Reduce number of fields required for sign-up

### ISSUE THREAD

**Issue by duxzitta** [openbankingnigeria/sandbox#12]
Email, password is OK. I don’t think we need to bother about password confirmation and strength. If you forget, you click reminder

**Comment by mujibishola** [comment]
Update from the conversation with @duxzitta 

1. No need for usernames as email is good enough
2. For the form field, If we have it as default in the input itself, no need to have another label describing it
3.  No need repeating password. Worst case, we can put an eye icon to show the password to the person and if they forget, they send a reminder email
